### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by FireFox101889** [inef1337/based#4]
how can i create a background script? I want to use natives every tick. Using a while loop inside of a job freezes the game which makes me think it's not running parallel. Thanks

**Comment by BaiFeng666** [comment]
background script put in based::hooks::run_script_threads

**Comment by FireFox101889** [comment]
> background script put in based::hooks::run_script_threads

what if i want to create another? thanks for the response, that solved that part.

**Comment by BaiFeng666** [comment]
maybe you need hook other game func

**Comment by inef1337** [comment]
Multithreading has been added.
