### ISSUE TITLE
any about global::queue->job() loop script example?

### ISSUE THREAD

**Issue by BaiFeng666** [inef1337/based#5]
`    auto task = []() {
                while (1) {
                    global::console->log("job work");
                    SwitchToFiber(GetCurrentFiber());
                }
            };

            global::queue->job(task);
`
I try to do like this, but game will frozen and crash

**Comment by inef1337** [comment]
The use of <code>global::queue->job();</code> was primarily intended for running natives within the GUI, and is not suitable for all types of features. I'm planning to update the underlying codebase over the weekend to provide clearer guidelines on how to implement features appropriately. In the meantime, a workaround would be to run all your features under the <code>run_script_threads</code> hook. 

Thank you for reporting.

**Comment by BaiFeng666** [comment]
> 

thank your reply
