### ISSUE TITLE
need WAIT(0)

### ISSUE THREAD

**Issue by BaiFeng666** [inef1337/based#6]
I am try to write a changePlayerModel func
and learn some menyoo source, like:
'bool Model::Load(DWORD timeOut) const
	{
		if (HAS_MODEL_LOADED(this->hash)) return true;
		else
		{
			REQUEST_MODEL(this->hash);

			for (timeOut += GetTickCount(); GetTickCount() < timeOut;)
			{
				if (HAS_MODEL_LOADED(this->hash))
					return true;
				WAIT(0);
			}
			return false;
		}
	}'

there hava a WAIT(0); but this is ScriptHookV's 
'///extern void(*scriptWait)(DWORD time);
__declspec(dllimport) void scriptWait(DWORD time);'

I dont know how to realize this, Many features cannot be achieved without it
Any help would be greatly appreciated~

**Comment by inef1337** [comment]
Hey there, I'll be implementing helper functions for these types of features in the weekend. Thank you for reporting.

**Comment by inef1337** [comment]
You can now use the <code>script::get_current()->yield()</code> function.
