### ISSUE TITLE
GET_DISPLAY_NAME_FROM_VEHICLE_MODEL() return value error

### ISSUE THREAD

**Issue by BaiFeng666** [inef1337/based#8]
'const char* GET_DISPLAY_NAME_FROM_VEHICLE_MODEL(Hash modelHash) { invoke<Hash>(0xB215AAC32D25D019, modelHash); } // 0xB215AAC32D25D019 0xEC86DF39 b323'
Need to be modified into

**Comment by BaiFeng666** [comment]
'const char* GET_DISPLAY_NAME_FROM_VEHICLE_MODEL(Hash modelHash) { invoke(0xB215AAC32D25D019, modelHash); } // 0xB215AAC32D25D019 0xEC86DF39 b323'

Need to be modified into
'const char* GET_DISPLAY_NAME_FROM_VEHICLE_MODEL(Hash modelHash) { return invoke<const char*>(0xB215AAC32D25D019, modelHash); } // 0xB215AAC32D25D019 0xEC86DF39 b323'

**Comment by inef1337** [comment]
I'll look into it.

**Comment by BaiFeng666** [comment]
> I'll look into it.

Some native functions have old names or incorrect parameter  , maybe consider updating Natives.hpp

**Comment by inef1337** [comment]
Yeah, good idea. Thank you

**Comment by BaiFeng666** [comment]
> Considering the status of the unresolved issue, may I infer that you are still encountering difficulty achieving functionality? If that is the case, here is a functional solution to retrieve the display name.
> 
> ![a](https://user-images.githubusercontent.com/130789342/237713767-b4be1780-d3eb-48e3-a1e5-c365c8342ceb.PNG)
> 
> Hope it helps.
Haha
Thank you for your help
but It's not hard for me,I just found a Native function return error,good man :)

**Comment by BaiFeng666** [comment]
Probably because you can't spawn dlc vehicles offline
a variable needs to be modified

**Comment by inef1337** [comment]
Here is the global: 4540726.
